default: &DEFAULT
  adapter: mysql2
  pool: 35
  read_timeout: 25
  connect_timeout: 5
  username: "root"
  password:
  host: "localhost"
  port: 3306
  charset: utf8
  collation: utf8_general_ci
  reconnect: true

development: &development
  <<: *DEFAULT
  database: blog_dev

test: &test
  <<: *DEFAULT
  database: blog_test

production: &production
  adapter: mysql2
  username: "be8edeadb9d89b"
  password: "fa23326e"