default: &DEFAULT
  adapter: mysql2
  pool: 35
  read_timeout: 25
  connect_timeout: 5
  username: "root"
  password:
  host: "localhost"
  port: 3306
  charset: utf8
  collation: utf8_general_ci
  reconnect: true

development: &development
  <<: *DEFAULT
  database: blog_dev

test: &test
  <<: *DEFAULT
  database: blog_test

production: &production
  url: 'mysql2://be8edeadb9d89b:fa23326e@us-cdbr-iron-east-05.cleardb.net/heroku_45aacccaef9cf49?reconnect=true'